### ISSUE TITLE
f.duplicated() not working in filter

### ISSUE THREAD

**Issue by antonio-yu** [pwwang/datar#72] opened 2021-11-02 05:46 UTC
Sometimes  I wanna keep all the duplicated rows. While in pandas, done like this 
mtcarss[mtcars.duplicated(keep=False)]
In datar, it does not work.
```
from datar.all import * 
from datar.datasets import mtcars

mtcars >> select('cyl','hp','gear','disp')>> filter(f.duplicated(keep=False))
```

But in  the follow two ways,it works.

```
# 1  f.series 

mtcars >> select('cyl','hp','gear','disp')>> filter(f.cyl.duplicated(keep=False))
```

```
# 2 select all the columns 

mtcars >> select('cyl','hp','gear','disp')>> filter(f['cyl'].duplicated(keep=False))
```
It seems that only series can be passed to the filter

**Comment by pwwang** [comment] 2021-11-02 06:25
In `datar`, `f.x` always refers to a column/series

`datar` designed to mimic data processing in `R`, so you probably need to think it in `R` way:
```python
>>> mtcars >> select('cyl','hp','gear','disp') >> group_by(f.cyl,f.hp,f.gear,f.disp) >> filter(n() > 1)
      cyl      hp    gear      disp
  <int64> <int64> <int64> <float64>
0       6     110       4     160.0
1       6     110       4     160.0
2       6     123       4     167.6
3       6     123       4     167.6
4       8     180       3     275.8
5       8     180       3     275.8
6       8     180       3     275.8

[Groups: cyl, hp, gear, disp (n=3)]
```

Or use the `duplicated()` function from `datar.base`, like the one from `r-base`:
```python
>>> mtcars >> select('cyl','hp','gear','disp') >> filter(duplicated(f) | duplicated(f, from_last=True))
                  cyl      hp    gear      disp
              <int64> <int64> <int64> <float64>
Mazda RX4           6     110       4     160.0
Mazda RX4 Wag       6     110       4     160.0
Merc 280            6     123       4     167.6
Merc 280C           6     123       4     167.6
Merc 450SE          8     180       3     275.8
Merc 450SL          8     180       3     275.8
Merc 450SLC         8     180       3     275.8
```

See also: https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/duplicated

**Comment by antonio-yu** [comment] 2021-11-03 00:42
I tried a `R` way, it took almost 90 minutes  to finish one filter.Here is the data information.

```
>data.shape 
(388013, 8)

> data.columns 
Index(['时间', '品牌', '商品', '标题', '链接', 'volume', '销额', 'avg'], dtype='object')

>data >> group_by(f.时间,f.商品) >> filter(n()>1)
87m5.2s taken.
Groups: ['时间', '商品'] (n=9930)
29095 rows × 8 columns   returned.
```

**Comment by pwwang** [comment] 2021-11-03 00:44
Yep, the `n()` needs to be optimized. Will put it in the plan.

How about the other one with `duplicated()`?

**Comment by antonio-yu** [comment] 2021-11-03 01:17
I am trying. It seems to take a very long time too. 10min passed already.

**Comment by antonio-yu** [comment] 2021-11-03 01:17
I am trying. It seems to take a very long time too. 10min passed already.

**Comment by antonio-yu** [comment] 2021-11-03 01:47
34m51.5s taken with `duplicated()` method.
In pandas, it could be done within second. Lots of space to optimize.

**Comment by antonio-yu** [comment] 2021-11-03 05:53
Since the `f.x` always refers to a column. 
There is no way to use apply in `mutate` .

```
def func(x,y):
    return x+y
#  pandas
mtcars['test']=mtcars.apply(lambda df : func(df['cyl'],df['gear']),axis=1)
#  datar , any way to implement  this?
mtcars >> mutate(test = f.apply(lambda df : func(df['cyl'],df['gear']),axis=1))
```

**Comment by pwwang** [comment] 2021-11-03 18:38
> Since the `f.x` always refers to a column. There is no way to use apply in `mutate` .
> 
> ```
> def func(x,y):
>     return x+y
> #  pandas
> mtcars['test']=mtcars.apply(lambda df : func(df['cyl'],df['gear']),axis=1)
> #  datar , any way to implement  this?
> mtcars >> mutate(test = f.apply(lambda df : func(df['cyl'],df['gear']),axis=1))
> ```

Actually, mixed-use of `datar` and `pandas` ways are not recommended. The only case that is acceptable is to use the functions from series/columns. For example:

```python
df >> mutate(m=f.a.mean())
```

To support something like `f.apply()` or `f.duplicated()` will add so much complexity at low-level bases.

But you can do it by registering it with your own verb:
```python
>>> from pipda import register_verb
>>> from datar.all import f, mutate
>>> from datar.datasets import mtcars
>>> 
>>> def func(x,y):
...     return x+y
... 
>>> @register_verb
... def myapply(data):
...   return data.apply(lambda df : func(df['cyl'],df['gear']), axis=1)
... 
>>> mtcars >> mutate(test = myapply(f))
                          mpg     cyl      disp      hp      drat        wt      qsec      vs      am    gear    carb      test
                    <float64> <int64> <float64> <int64> <float64> <float64> <float64> <int64> <int64> <int64> <int64> <float64>
Mazda RX4                21.0       6     160.0     110      3.90     2.620     16.46       0       1       4       4      10.0
Mazda RX4 Wag            21.0       6     160.0     110      3.90     2.875     17.02       0       1       4       4      10.0
Datsun 710               22.8       4     108.0      93      3.85     2.320     18.61       1       1       4       1       8.0
Hornet 4 Drive           21.4       6     258.0     110      3.08     3.215     19.44       1       0       3       1       9.0
Hornet Sportabout        18.7       8     360.0     175      3.15     3.440     17.02       0       0       3       2      11.0
Valiant                  18.1       6     225.0     105      2.76     3.460     20.22       1       0       3       1       9.0
Duster 360               14.3       8     360.0     245      3.21     3.570     15.84       0       0       3       4      11.0
Merc 240D                24.4       4     146.7      62      3.69     3.190     20.00       1       0       4       2       8.0
Merc 230                 22.8       4     140.8      95      3.92     3.150     22.90       1       0       4       2       8.0
Merc 280                 19.2       6     167.6     123      3.92     3.440     18.30       1       0       4       4      10.0
Merc 280C                17.8       6     167.6     123      3.92     3.440     18.90       1       0       4       4      10.0
Merc 450SE               16.4       8     275.8     180      3.07     4.070     17.40       0       0       3       3      11.0
Merc 450SL               17.3       8     275.8     180      3.07     3.730     17.60       0       0       3       3      11.0
Merc 450SLC              15.2       8     275.8     180      3.07     3.780     18.00       0       0       3       3      11.0
Cadillac Fleetwood       10.4       8     472.0     205      2.93     5.250     17.98       0       0       3       4      11.0
Lincoln Continental      10.4       8     460.0     215      3.00     5.424     17.82       0       0       3       4      11.0
Chrysler Imperial        14.7       8     440.0     230      3.23     5.345     17.42       0       0       3       4      11.0
Fiat 128                 32.4       4      78.7      66      4.08     2.200     19.47       1       1       4       1       8.0
Honda Civic              30.4       4      75.7      52      4.93     1.615     18.52       1       1       4       2       8.0
Toyota Corolla           33.9       4      71.1      65      4.22     1.835     19.90       1       1       4       1       8.0
Toyota Corona            21.5       4     120.1      97      3.70     2.465     20.01       1       0       3       1       7.0
Dodge Challenger         15.5       8     318.0     150      2.76     3.520     16.87       0       0       3       2      11.0
AMC Javelin              15.2       8     304.0     150      3.15     3.435     17.30       0       0       3       2      11.0
Camaro Z28               13.3       8     350.0     245      3.73     3.840     15.41       0       0       3       4      11.0
Pontiac Firebird         19.2       8     400.0     175      3.08     3.845     17.05       0       0       3       2      11.0
Fiat X1-9                27.3       4      79.0      66      4.08     1.935     18.90       1       1       4       1       8.0
Porsche 914-2            26.0       4     120.3      91      4.43     2.140     16.70       0       1       5       2       9.0
Lotus Europa             30.4       4      95.1     113      3.77     1.513     16.90       1       1       5       2       9.0
Ford Pantera L           15.8       8     351.0     264      4.22     3.170     14.50       0       1       5       4      13.0
Ferrari Dino             19.7       6     145.0     175      3.62     2.770     15.50       0       1       5       6      11.0
Maserati Bora            15.0       8     301.0     335      3.54     3.570     14.60       0       1       5       8      13.0
Volvo 142E               21.4       4     121.0     109      4.11     2.780     18.60       1       1       4       2       8.0
```

**Comment by pwwang** [comment] 2021-11-03 18:45
> 34m51.5s taken with `duplicated()` method. In pandas, it could be done within second. Lots of space to optimize.

For `duplicated()`, could you test this method on your dataset? It helps me identify where it gets slowing down:
```python
>>> from pipda import register_verb
>>> from datar.datasets import mtcars
>>> from datar.all import *

>>> @register_verb
... def duplicated(df):
...   return df.duplicated(keep=False)

>>> mtcars >> select(f.cyl, f.hp, f.gear, f.disp) >> filter(duplicated(f))
                  cyl      hp    gear      disp
              <int64> <int64> <int64> <float64>
Mazda RX4           6     110       4     160.0
Mazda RX4 Wag       6     110       4     160.0
Merc 280            6     123       4     167.6
Merc 280C           6     123       4     167.6
Merc 450SE          8     180       3     275.8
Merc 450SL          8     180       3     275.8
Merc 450SLC         8     180       3     275.8
```

**Comment by pwwang** [comment] 2021-11-03 19:43
I have the following tested, and both of them finished in less than a second:

```python
>>> mc = bind_rows(mtcars, *( [mtcars] * 10000))
>>>
>>> @register_verb
... def pd_duplicated(df):
...     return df.duplicated(keep=False)
... 
>>> mc >>  select(f.cyl, f.hp, f.gear, f.disp) >> filter(pd_duplicated(f))
```

```python
>>> mc >> select(f.cyl, f.hp, f.gear, f.disp) >> filter(duplicated(f) | duplicated(f, from_last=True))
```

If possible, could you share your data for testing?

**Comment by antonio-yu** [comment] 2021-11-04 01:05
My bad.
I wrote a  wrong syntax for  duplicated(f) method
```test >> group_by(f.period,f.product) >> filter(duplicated(f))```
It should be  select other than groupb_by here in this syntax. 
Id did finish in less than a second.

So the only factor that slows down the code  is  grouped data .

**Comment by antonio-yu** [comment] 2021-11-04 01:13
By the way , no offense, I also tried the ` n()` method in `fast_filter` of siuba, it finished in 0.4s.
```
from siuba import * 
from siuba.experimental.pd_groups import fast_summarize,fast_mutate,fast_filter
from siuba.dply.vector import n

mc >> group_by(_.cyl,_.gear,_.disp) >> fast_filter(n(_.cyl)>1)
```

**Comment by antonio-yu** [comment] 2021-11-04 01:15
>Actually, mixed-use of datar and pandas ways are not recommended. The only case that is acceptable is to use the functions from series/columns.

I got it now, `@register_verb ` would help a lot

**Comment by pwwang** [comment] 2021-11-04 16:15
> By the way , no offense, I also tried the ` n()` method in `fast_filter` of siuba, it finished in 0.4s.
> 
> ```
> from siuba import * 
> from siuba.experimental.pd_groups import fast_summarize,fast_mutate,fast_filter
> from siuba.dply.vector import n
> 
> mc >> group_by(_.cyl,_.gear,_.disp) >> fast_filter(n(_.cyl)>1)
> ```

No, no offense at all. I understand the difference. `datar` tends to implement `dplyr`'s syntax in the first place. So `df.apply()` was simply used. There's definitely places for optimizations.

**Comment by pwwang** [comment] 2021-12-29 19:51
> By the way , no offense, I also tried the ` n()` method in `fast_filter` of siuba, it finished in 0.4s.
> 
> ```
> from siuba import * 
> from siuba.experimental.pd_groups import fast_summarize,fast_mutate,fast_filter
> from siuba.dply.vector import n
> 
> mc >> group_by(_.cyl,_.gear,_.disp) >> fast_filter(n(_.cyl)>1)
> ```

@antonio-yu at which version of siuba you run this?

I cannot run this, always raises `AttributeError: module 'pandas.core.algorithms' has no attribute 'take_1d'`

Would you check the syntax?

**Comment by pwwang** [comment] 2021-12-29 19:54
Also, you mentioned that it took 0.4s. With datar, it takes even less:
```python
# jupyter book cell#1
from datar.all import *
from datar.datasets import mtcars

from pipda import options
options.assume_all_piping = True

# jupyter book cell#2
%%timeit
mtcars >> group_by(f.cyl, f.gear, f.disp) >> filter(n() > 1)

# 82.8 ms ± 6.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by rleyvasal** [comment] 2022-01-05 22:29
I can confirm that finding duplicates takes less than 0.4s

Running the code below, it gets executed in 0.1s in VSCode  -  not as accurate as %%timeit in Jupyter notebooks

````python
mtcars >> group_by(f.cyl, f.gear, f.disp) >> filter(n() > 1)

````

**Comment by machow** [comment] 2022-01-06 00:15
It makes sense to me that this would run quickly in either library, since there aren't a lot of groups in the data! In practice, the fast functions should become more useful as the number of [groups goes into the thousands](https://siuba.readthedocs.io/en/latest/developer/pandas-group-ops.html), since initializing DataFrames is relatively slow.

FWIW I couldn't even run `mtcars >> fast_filter(n(_) > 1)` in siuba, due to a bug 😅. (Opened a [PR to fix](https://github.com/machow/siuba/pull/363)).

It seems like these kinds of issues sit at the intersection of there being an easy and fast pandas method (`DataFrame.duplicated()`), and the dplyr way taking a lot of work to support for 10,000+ groups. (but other dplyr ways like group_by -> count -> filter probably being very fast?).

Here's code comparing the dplyr approach with datar 

**Setup**

```python
from datar.all import *
import numpy as np
import pandas as pd
import timeit

np.random.seed(123)
students = pd.DataFrame({
    'student_id': np.repeat(np.arange(2000), 10),
    'course_id': np.random.randint(1, 20, 20000),
    'score': np.random.randint(1, 100, 20000)
})
```

**Datar**

```python
from datar.all import *

# note I got an error: 'group_by' is not registered for type: <class 'pipda.symbolic.DirectRefAttr'>.
# but am curious what these timings look like
%%timeit
students >> group_by(f.student_id) >> filter(n() > 1)

%%timeit
students >> group_by(f.student_id) >> count() >> filter(f.n > 1)
```

**Siuba**

Note how the fast_filter approach actually just does about the same as using group_by + count..!

```python
# note that I had to downgrade to pandas 1.1.0 for fast_filter to work :/

import siuba as sb
from siuba.dply import vector as v
from siuba.experimental.pd_groups import fast_filter

# 162 ms ± 4.54 ms per loop
%%timeit
students.groupby("student_id") >> sb.filter(v.n(sb._) > 1)

# 1.87 ms ± 26.8 µs per loop
%%timeit
students.groupby("student_id") >> sb.count() >> sb.filter(sb._.n > 1)

# 2.12 ms ± 24.3 µs per loop
%%timeit
students.groupby("student_id") >> fast_filter(v.n(sb._) > 1)
```

**Comment by pwwang** [comment] 2022-01-06 17:54
@machow 

Thanks for the feedback.
For `datar` to work with `%%timeit`, we need:

```diff
from datar.all import *
+ from pipda import options
+ options.assume_all_piping = True

# 3.47 s ± 124 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%%timeit
students >> group_by(f.student_id) >> filter(n() > 1)

# 7.03 s ± 738 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%%timeit
students >> group_by(f.student_id) >> count() >> filter(f.n > 1)
```


But you are right anyway, with a number of groups, `datar` needs to void initiating those dataframes. 

Working on a version to optimize this. The difficult part is to parse the arguments passed to `filter()` and see if they can be optimized.

**Comment by machow** [comment] 2022-01-06 19:13
Ah, thanks--got it running now!

I've been curious about datar (especially the AST / source parsing parts 😮), so this is super handy to see. I wonder if the biggest bottleneck in the last example is the count function, since it is passing to summarize (which splits into sub DataFrames?)

I realized that siuba ungroups after count, so the slowness of the datar filter in the last example was likely because it's grouped. Ungrouped it cuts the time in half for me (from ~6s to ~3s). It seems like the big bottleneck is using summarize to do the counting.

![image](https://user-images.githubusercontent.com/2574498/148436233-a23e79db-a1a4-40d0-af01-70c52be4c040.png)

In case it's useful, I ended up just using fast pandas methods like [`.size()` under the hood](https://github.com/machow/siuba/blob/main/siuba/dply/verbs.py#L892) for count, which was way less headache than working on the "fast verbs" in siuba. But also, maybe crazy idea but FWIW the underlying tools for the fast verbs in siuba only really depends on pandas, so could in theory be pulled out? 

* https://github.com/machow/siuba/blob/main/siuba/experimental/pd_groups/groupby.py
* [ADR on above file (may be a little out of date)]( https://github.com/machow/siuba/blob/main/examples/architecture/007-how-pandas-groupby-works.ipynb)

**Comment by pwwang** [comment] 2022-01-06 19:26
Thanks!
This is super clear to see where the time's been eaten up. And it proves my thought that the split-join process is a bad route here (which is pretty obvious though). Instead, I should skip it and use native pandas way, as you did for siuba. Trying to figure out a way to convert the arguments (which are `pipda.symbolic.Symbolic objects`) to a function to pass to `pandas.GroupBy.filter()`.

**Comment by GitHunter0** [comment] 2022-01-16 02:23
Just to mention, @machow and @pwwang , you are doing a huge contribution to the community by bringing the best part of R to fill the messiest most annoying part of Python, which in my opinion is data wrangling.

**Comment by pwwang** [comment] 2022-03-07 03:53
@antonio-yu Would you mind using v0.6.0 to rerun the example to see the performance? Thanks!

**Comment by antonio-yu** [comment] 2022-03-23 01:30
@pwwang, 
I tried the example by V0.6.3, not working . 

```
>>mtcars >> select('cyl','hp','gear','disp')>> filter(f.duplicated(keep=False))

Traceback (most recent call last):
  File "D:\programfiles\anaconda\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'duplicated'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\programfiles\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-b2b7002e2ab8>", line 1, in <module>
    mtcars >> select('cyl','hp','gear','disp')>> filter(f.duplicated(keep=False))
  File "D:\programfiles\anaconda\lib\site-packages\pipda\function.py", line 134, in _pipda_eval
    args = evaluate_expr(bondargs.args, data, context)
  File "D:\programfiles\anaconda\lib\site-packages\pipda\utils.py", line 206, in evaluate_expr
    return expr.__class__(
  File "D:\programfiles\anaconda\lib\site-packages\pipda\utils.py", line 207, in <genexpr>
    (evaluate_expr(elem, data, context) for elem in expr)
  File "D:\programfiles\anaconda\lib\site-packages\pipda\utils.py", line 202, in evaluate_expr
    return expr._pipda_eval(data, context)
  File "D:\programfiles\anaconda\lib\site-packages\pipda\function.py", line 83, in _pipda_eval
    func = evaluate_expr(func, data, context)
  File "D:\programfiles\anaconda\lib\site-packages\pipda\utils.py", line 202, in evaluate_expr
    return expr._pipda_eval(data, context)
  File "D:\programfiles\anaconda\lib\site-packages\pipda\symbolic.py", line 73, in _pipda_eval
    return context.getattr(parent, self._pipda_ref, self._pipda_level)
  File "D:\programfiles\anaconda\lib\site-packages\datar\core\contexts.py", line 45, in getattr
    return parent[ref]
  File "D:\programfiles\anaconda\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\programfiles\anaconda\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'duplicated
```



`

**Comment by pwwang** [comment] 2022-03-23 02:16
@antonio-yu You still need to do it this way:

> In `datar`, `f.x` always refers to a column/series
> 
> `datar` is designed to mimic data processing in `R`, so you probably need to think it in `R` way:
> 
> ```python
> >>> mtcars >> select('cyl','hp','gear','disp') >> group_by(f.cyl,f.hp,f.gear,f.disp) >> filter(n() > 1)
>       cyl      hp    gear      disp
>   <int64> <int64> <int64> <float64>
> 0       6     110       4     160.0
> 1       6     110       4     160.0
> 2       6     123       4     167.6
> 3       6     123       4     167.6
> 4       8     180       3     275.8
> 5       8     180       3     275.8
> 6       8     180       3     275.8
> 
> [Groups: cyl, hp, gear, disp (n=3)]
> ```
> 
> Or use the `duplicated()` function from `datar.base`, like the one from `r-base`:
> 
> ```python
> >>> mtcars >> select('cyl','hp','gear','disp') >> filter(duplicated(f) | duplicated(f, from_last=True))
>                   cyl      hp    gear      disp
>               <int64> <int64> <int64> <float64>
> Mazda RX4           6     110       4     160.0
> Mazda RX4 Wag       6     110       4     160.0
> Merc 280            6     123       4     167.6
> Merc 280C           6     123       4     167.6
> Merc 450SE          8     180       3     275.8
> Merc 450SL          8     180       3     275.8
> Merc 450SLC         8     180       3     275.8
> ```
> 
> See also: https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/duplicated

**Comment by antonio-yu** [comment] 2022-03-23 03:31
@pwwang
OH ,my bad, I made a s mistake. I thought you asked me to try the 'f.duplicated()' ,

I tried  `'df >>group_by(f.时间,f.商品) >> filter(n()>1)'` , now `n()` function works very well and is also fast.

**Comment by pwwang** [comment] 2022-03-23 03:32
@antonio-yu Cool. 
Closing. Feel free to open a new one if you have further questions.

**Closed by pwwang** 2022-03-23 03:32 UTC
Labels: optim
