### ISSUE TITLE
`group_by`  TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by rleyvasal** [pwwang/datar#35] opened 2021-07-12 21:00 UTC
# Issue

`group_by`  TypeError: '<' not supported between instances of 'str' and 'int'

# Steps to replicate 

`from datar.all import *`
`df_test = pd.read_excel("https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx")`
`df_test >> group_by(f.Description)`

# Snapshot of error message

<img width="677" alt="group_by_error" src="https://user-images.githubusercontent.com/61335136/125354939-41a5bb00-e319-11eb-8609-f2a2312001ea.PNG">

**Comment by pwwang** [comment] 2021-07-12 21:14
There are mixed integers and strings in column `Description`, you need to clean to up and then do the groupby:

```python
>>> df_test >> mutate(Description=as_character(f.Description)) >> group_by(f.Description)
       InvoiceNo StockCode                          Description  ...  UnitPrice CustomerID         Country
        <object>  <object>                             <object>  ...  <float64>  <float64>        <object>
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER  ...       2.55    17850.0  United Kingdom
1         536365     71053                  WHITE METAL LANTERN  ...       3.39    17850.0  United Kingdom
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER  ...       2.75    17850.0  United Kingdom
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE  ...       3.39    17850.0  United Kingdom
...          ...       ...                                  ...  ...        ...        ...             ...
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.  ...       3.39    17850.0  United Kingdom
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS  ...       0.85    12680.0          France
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL   ...       2.10    12680.0          France
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL   ...       4.15    12680.0          France
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE  ...       4.15    12680.0          France
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT             4.95    12680.0          France

[Groups: Description (n=4224)]
[541909 rows x 8 columns]
```

**Comment by pwwang** [comment] 2021-07-12 21:16
Or you can specify the `dtype` while `read_excel`:
```python
df_test = pd.read_excel(
  "https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx", 
  dtype={"Description": str}
)
```

Seel also: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_excel.html

**Comment by rleyvasal** [comment] 2021-07-12 21:38
Thanks for the quick response @pwwang .

Changing the data type works for me. 

BTW, is there a way to display variable type  `str` under the variable name?  - after changing data type to `str` still shows `<object>` under the variable name `Description`

**Comment by pwwang** [comment] 2021-07-12 22:04
The types shown under the column names are fetched by `x.dtype.name`

However, the problem is that `numpy`/`pandas` cannot recognize `str` it a "str" dtype:
```python
>>> df = tibble(x=[1,2,3])
>>> df.x.dtype.name
'int64'
>>> df.x.astype(str).dtype.name
'object'
>>> df.x.astype(str).dtype.type
<class 'numpy.object_'>
>>> # not even numpy.str_
>>> df.x.astype(np.str_).dtype.name
'object'
```

Unless we are using pandas' nullable string dtype:
```python
>>> df.x.astype('string').dtype.name
'string'
>>> df.x.astype(pd.StringDtype()).dtype.name
'string'
```

However, it may lead to different behaviors, especially with `NA` data. For example:
```python
>>> df = tibble(x=[1,2,NA])
>>> df.x.astype(str).tolist()
['1.0', '2.0', 'nan']
>>> df.x.astype('string').tolist()
['1.0', '2.0', <NA>]
```

Looks like pandas' `StringDtype` makes more sense. But `numpy` is not aware of the existence of pandas' `<NA>`, which causes quite an amount of incompatibilities in downstream calculations/string operations.

Maybe an option is to add a `dtype` argument for `as_character()` for users to choose the dtype they want. But by doing that, they should be aware of the different behaviors.

**Comment by pwwang** [comment] 2021-07-12 22:14
Another option I can think of is to attach the type name to `x.dtype` (say `x.dtype._rawname`) inside `as_character()` or other type casting functions. While displaying, try fetching `x.dtype._rawname` first, if failed, try `x.dtype.name`.

But this only works with `as_*()` type casting functions. It won't work with `df['x'] = df.x.astype(str)`.

**Comment by pwwang** [comment] 2021-07-12 22:47
Closing this in favor of #36.

**Closed by pwwang** 2021-07-12 22:47 UTC
